---
- name: Update apt packages
  become: true
  become_user: root
  ansible.builtin.apt:
    upgrade: "no"
    update_cache: true

- name: Install python3-debian
  become: true
  become_user: root
  ansible.builtin.package:
    name: python3-debian
    state: present

- name: Add kubernetes apt repository
  become: true
  become_user: root
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: https://pkgs.k8s.io/core:/stable:/{{ kubectl_version }}/deb/
    signed_by: "https://pkgs.k8s.io/core:/stable:/{{ kubectl_version }}\
                /deb/Release.key"
    suites: [/]
    state: present
    enabled: true

- name: Update apt packages
  become: true
  become_user: root
  ansible.builtin.apt:
    upgrade: "no"
    update_cache: true
