---
- name: Include task list in play
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Install kubectl
  become: true
  become_user: root
  ansible.builtin.package:
    name: kubectl
    state: present
